apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: polaris
  namespace: flux-system
spec:
  chart:
    spec:
      chart: polaris
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
      version: 3.0.1
  interval: 1h0m0s
  releaseName: polaris
  targetNamespace: polaris
