apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vpa
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
      version: 0.2.2
  interval: 1h0m0s
  releaseName: vpa
  targetNamespace: vpa
  #values:
  #  recommender:
  #    extraArgs:
  #      prometheus-address: |
  #        http://prometheus-operator-prometheus.prometheus-operator.svc.cluster.local:9090
  #      storage: prometheus