---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: official-helm-repo
      version: 1.41.3
  interval: 1h0m0s
  releaseName: nginx-ingress
  targetNamespace: nginx-ingress
  values:
    defaultBackend:
      enabled: true
    controller: 
      service: 
        externalTrafficPolicy: Local
        #annotations: 
        #  metallb.universe.tf/address-pool: default
      ingressClass: "nginx-default"
