---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1m
  path: ./deployments/prometheus-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s

