apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: polaris
---
apiVersion: v1
kind: Namespace
metadata:
  name: vpa
---
apiVersion: v1
kind: Namespace
metadata:
  name: goldilocks
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-operator


