apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-app
  template:
    metadata:
      labels:
        app: testing-app
    spec:
      containers:
      - name: testing-app
        image: sinmsinm/peumaudio:0.0.0
        ports:
        - containerPort: 8888
