apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vpa
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
      version: 3.2.1
  interval: 1h0m0s
  releaseName: goldilocks
  targetNamespace: goldilocks
