apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.yaml
configMapGenerator:
  - name: prometheus-values
    namespace: flux-system
    files:
      - prometheus-values.yaml=prometheus-values.yaml
configurations:
- kustomization-config.yaml
