apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: monitoring
  install:
    createNamespace: true
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "16.11.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-values
    valuesKey: prometheus-values.yaml